id: P010587
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG10772
  title: གསུང་འབུམ། ཡེ་ཤེ་རྒྱ་མཚོ། ༼སེར་སྨད་གྲྭ་ཚང་པར་མ།༽
  author: ''
  volumes:
    a9b3c5af8ba941f4b756f9d94e42cbd8:
      image_group_id: I1KG10792
      title: ''
      volume_number: 1
      total_pages: 540
      base_file: v001.txt
