id: I82BE984E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:43:51+00:00'
last_modified: '2022-06-16T06:21:04.539310+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG10772
  title: གསུང་འབུམ། ཡེ་ཤེ་རྒྱ་མཚོ། ༼སེར་སྨད་གྲྭ་ཚང་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3434':
      image_group_id: I1KG10792
      title: ''
      total_pages: 540
      order: 1
      base_file: 3434.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
